spring:
  profiles:
    active: dev

   #mvc:
    #  view:
    #    prefix: /pages/
    #    suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.donkey.demo.domain

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

---
#下面这一行务必不能少，区分不同配置，而且必须是三个字符"-"
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/red_packet?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 30
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1765000

  redis:
    host: 172.16.2.147
    port: 6379
    password:
    max-active: 30
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout:  0


---
# 生产环境配置

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tt.china.ip.parser.domain
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/red_packet?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 30
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1765000

  redis:
    host: 172.16.2.147
    port: 6379
    password:
    max-active: 30
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout:  0


